In [421]:
import pandas as pd
import requests
import re
from bs4 import BeautifulSoup

In [423]:
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

In [424]:
soup = BeautifulSoup(webpage,'lxml')

In [425]:
company=soup.find_all('div',class_="companyCardWrapper__primaryInformation")

In [426]:
len(company)

20

In [471]:
name=[]
rating=[]
reviews=[]
type_and_location=[]


for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div',class_='rating_text').text.strip())
    reviews.append(i.find('span', class_="companyCardWrapper__companyRatingCount").text.strip())
    type_and_location.append(i.find('span',class_='companyCardWrapper__interLinking').text.strip())
d = {'name':name,'rating':rating,'reviews':reviews,'type_and_location':type_and_location}
df = pd.DataFrame(d)

In [473]:
df

,name,rating,reviews,type_and_location
0,Ericsson,3.9,(8.3k),Telecom | Noida +163 other locations
1,Samsung,3.9,(8.3k),Consumer Electronics & Appliances | Noida +586...
2,Dr. Reddy's,4.0,(8.1k),Pharma | Hyderabad +214 other locations
3,Optum Global Solutions,4.0,(7.8k),IT Services & Consulting | Hyderabad +68 other...
4,Delhivery,3.8,(7.7k),Logistics | Gurugram +760 other locations
5,JPMorgan Chase & Co.,3.8,(7.7k),Financial Services | Bengaluru +55 other locat...
6,JSW Steel,3.9,(7.7k),Iron & Steel | Ballari +193 other locations
7,ICICI Prudential Life Insurance,3.9,(7.7k),Insurance | Mumbai +506 other locations
8,Hexaware Technologies,3.4,(7.5k),IT Services & Consulting | Chennai +69 other l...
9,HGS,3.7,(7.5k),BPO | Bengaluru +121 other locations
10,Jana Small Finance Bank,3.8,(7.5k),Banking | Bengaluru +418 other locations
11,Ujjivan Small Finance Bank,4.0,(7.5k),Banking | Bengaluru +536 other locations
12,Sun Pharmaceutical Industries,4.1,(7.5k),Pharma | Vadodara +264 other locations
13,Amazon Development Centre India,3.8,(7.4k),Internet | Hyderabad +146 other locations
14,Lupin,4.1,(7.3k),Pharma | Pune +203 other locations
15,Ekart Logistics,3.9,(7.3k),Logistics | Bengaluru +742 other locations
16,L&T Construction,4.0,(7.2k),Engineering & Construction | Chennai +433 othe...
17,Zydus Lifesciences,4.0,(7.2k),Pharma | Ahmedabad +178 other locations
18,Hindustan Unilever,4.2,(7.1k),FMCG | Mumbai +540 other locations
19,KPMG India,3.4,(7.1k),Management Consulting | Bengaluru +112 other l...

In [508]:
final = pd.DataFrame()

for j in range(1,100):
    url='https://www.ambitionbox.com/list-of-companies?page={}'.format(j)

    headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
    webpage = requests.get(url,headers=headers).text
    
    soup = BeautifulSoup(webpage,'lxml')
    
    company=soup.find_all('div',class_="companyCardWrapper__primaryInformation")
    name=[]
    rating=[]
    reviews=[]
    type_and_location=[]
    
    
    for i in company:
        
        name.append(i.find('h2').text.strip())
        
        rating.append(i.find('div',class_='rating_text').text.strip())
        reviews.append(i.find('span', class_="companyCardWrapper__companyRatingCount").text.strip())
        type_and_location.append(i.find('span',class_='companyCardWrapper__interLinking').text.strip())
    d = {'name':name,'rating':rating,'reviews':reviews,'type_and_location':type_and_location}
    df = pd.DataFrame(d)
    final = pd.concat([final, df], ignore_index=True)

In [509]:
final

,name,rating,reviews,type_and_location
0,TCS,3.3,(1.1L),IT Services & Consulting | Bengaluru +439 othe...
1,Accenture,3.7,(72.2k),IT Services & Consulting | Bengaluru +255 othe...
2,Wipro,3.6,(64.1k),IT Services & Consulting | Hyderabad +371 othe...
3,Cognizant,3.6,(60.4k),IT Services & Consulting | Hyderabad +232 othe...
4,Capgemini,3.7,(52.1k),IT Services & Consulting | Bengaluru +182 othe...
...,...,...,...,...
1975,Hi Tech Gears,3.9,(541),Auto Components | Bhiwadi +29 other locations
1976,Roop Polymers,3.9,(540),Auto Components | Gurugram +25 other locations
1977,Dhani Healthcare,3.5,(540),FinTech | Gurugram +81 other locations
1978,Maini Precision Products,3.4,(540),Auto Components | Bengaluru +11 other locations
1979,RAK Ceramics,3.8,(540),Building Material | Mumbai +61 other locations

In [512]:
final.to_csv("ambitionbox_companies_dataset.csv", index=False)